# -*- coding:utf-8 -*-
############################################
#Auther:：Sen
#Version：Autotestplat-V6.0
############################################
from django.urls import path
from . import views, views_index, views_requirements, views_aitestcase, views_iteration, views_bug, views_report, \
    views_aitestcasetemp, views_worktask, views_quality, views_sendemail
from . import views_user
from . import views_product
from . import views_interface
from . import views_systemsettings
from . import views_interfacetestplan
from . import views_interfacereport
from . import views_performance
from . import views_apptestcase
from . import views_webtestcase
from . import views_envconfig

urlpatterns = [
    path('index/', views_index.indexView, name='index'),
    path('ai/', views_index.aiPage, name='ai'),
    path('requirements/', views_requirements.RequirementsView, name='requirements'),
    path('requirements/getTableData/', views_requirements.loadRequirements),
    path('requirements/add/', views_requirements.addRequirements),
    path('requirements/mod/', views_requirements.updateRequirements),
    path('requirements/del/', views_requirements.deleteRequirements),
    path('requirements/totestcase/', views_requirements.requireTotestcase),
    path('requirements/getReToCaseDetail/<str:require_id>/', views_requirements.getReToCaseDetail, name='requirecasedetail'),
    path('requirements/getTableData/<str:require_id>/', views_aitestcase.loadretoAiTestcaseTable),
    path('iteration/', views_iteration.IterationView, name='iteration'),
    path('iteration/getTableData/', views_iteration.loadIteration),
    path('iteration/add/', views_iteration.addIteration),
    path('iteration/mod/', views_iteration.updateIteration),
    path('iteration/del/', views_iteration.deleteIteration),
    path('iteration/report/', views_iteration.reportIteration),
    path('aitestcase/', views_aitestcase.getAiView, name='aitestcase'),

    path('aitestcasetemp/', views_aitestcasetemp.getAiView, name='aitestcasetemp'),
    path('aitestcasetemp/getTableData/', views_aitestcasetemp.loadAiTestcaseTable),
    path('aitestcasetemp/delAitestcase/', views_aitestcasetemp.deleteAitestcase),
    path('aitestcasetemp/showModAiTestcase/', views_aitestcasetemp.showModAiTestcase),
    path('aitestcasetemp/modAitestcase/', views_aitestcasetemp.modAitestcase),
    path('aitestcasetemp/addAitestcase/', views_aitestcasetemp.addAitestcase),
    path('aitestcasetemp/saveFromChat/', views_aitestcasetemp.saveAiTestcaseFromChat),

    path('aitestcase/getSearchSelect/', views_aitestcase.loadAiOptions),
    path('aitestcase/getTableData/', views_aitestcase.loadAiTestcaseTable),
    path('aitestcase/addAitestcase/', views_aitestcase.addAitestcase),
    path('aitestcase/delAitestcase/', views_aitestcase.deleteAitestcase),
    path('aitestcase/showModAiTestcase/', views_aitestcase.showModAiTestcase),
    path('aitestcase/modAitestcase/', views_aitestcase.modAitestcase),
    path('aitestcase/showCopyAiTestcase/', views_aitestcase.showCopyAiTestcase),
    path('aitestcase/copyAitestcase/', views_aitestcase.copyAitestcase),
    path('aitestcase/runAitestcase/',views_aitestcase.runAitestcase),
    path('aitestcase/showRunAiTestcase/', views_aitestcase.showRunAiTestcase),
    path('bug/', views_bug.bugView, name='buglist'),
    path('bug/getTableData/', views_bug.loadBug),
    path('bug/add/', views_bug.addBug),
    path('bug/mod/', views_bug.updateBug),
    path('bug/del/', views_bug.deleteBug),
    path('testreport/', views_report.testReportView, name='testreport'),
    path('testreport/getTableData/', views_report.loadTestReport),
    path('testreport/getTestReportDetail/<str:testreport_id>/', views_report.getTestReportDetail, name='testreportdetail'),
    path('testreport/del/', views_report.deleteTestReport),
    path('user/', views_user.userView, name='user'),
    path('user/getSearchSelect/', views_user.loadUserRoleSearch),
    path('user/getAddSelect/', views_user.loadAddOptions),
    path('user/getSelect/', views_user.loadOptions),
    path('user/getTableData/', views_user.loadUser),
    path('user/add/', views_user.addUser),
    path('user/mod/<str:userName>', views_user.updateUser),
    path('user/del/', views_user.deleteUser),
    path('user/get/', views_user.getUserProduct),
    path('user/set/', views_user.setUserProduct),
    path('user/set/iteration/', views_user.setUserIteration),
    path('login/', views_user.loginView, name='login'),
    path('login/identify/', views_user.login),
    path('login/last/', views_user.lastLogin),
    path('logout/', views_user.logout),
    path('systemsettings/', views_systemsettings.showSystemSettings, name='parasettings'),
    path('systemsettings/getTableData/', views_systemsettings.loadSystemSettings),
    path('systemsettings/add/', views_systemsettings.addSettingsPara),
    path('systemsettings/del/', views_systemsettings.delSettingsPara),
    path('systemsettings/showMod/', views_systemsettings.showModSettingsPara),
    path('systemsettings/mod/', views_systemsettings.saveModSettingsPara),
    path('systemsettings/getSearchSelect/', views_systemsettings.loadParaTypeSearch),
    path('systemsettings/getSelect/', views_systemsettings.loadParaOption),
    path('product/', views_product.productView, name='product'),
    path('product/getTableData/', views_product.loadProduct),
    path('product/add/', views_product.addProduct),
    path('product/mod/', views_product.updateProduct),
    path('product/del/', views_product.deleteProduct),
    path('apitestcase/module/get/', views_interface.loadModule),
    path('apitestcase/addModule/', views_interface.addModule),
    path('apitestcase/modModule/', views_interface.modModule),
    path('apitestcase/delModule/', views_interface.deleteModule),
    path('apitestcase/', views_interface.getApiView,name='apitestcase'),
    path('apitestcase/getTableData/<str:menu_module_id>/', views_interface.loadApiTestcaseTable),
    path('apitestcase/show_add_window/<str:menu_module_id>', views_interface.showAddWindow),
    path('apitestcase/add/', views_interface.addInterfaces),
    path('apitestcase/search/', views_interface.searchInterface),
    path('apitestcase/show_edit_interface/<str:edit_id>/<str:action>/', views_interface.showEditInterface),
    path('apitestcase/save_edit_interface/<str:edit_id>/', views_interface.saveEditInterface),
    path('apitestcase/save_copy_interface/<str:edit_id>/', views_interface.saveCopyInterface),
    path('apitestcase/del/', views_interface.delInterface),
    path('apitestcase/send/', views_interface.startInterfaceSend),
    path('apitestcase/show_request_data/', views_interface.showRequestData),
    path('apitestplan/', views_interfacetestplan.interfaceTestplan,name='apitestplan'),
    path('apitestplan/add/', views_interfacetestplan.addTestplan),
    path('apitestplan/show_edit_testplan/', views_interfacetestplan.showEditTestplan),
    path('apitestplan/mod/', views_interfacetestplan.saveEditTestplan),
    path('apitestplan/update/', views_interfacetestplan.updateTestplanInterface),
    path('apitestplan/del_row/', views_interfacetestplan.delRow),
    path('apitestplan/del_row_edit/', views_interfacetestplan.delRowEdit),
    path('apitestplan/del/', views_interfacetestplan.delTestplan),
    path('apitestplan/search/', views_interfacetestplan.searchTestplan),
    path('apitestplan/apitestcase/search/', views_interfacetestplan.searchTestplanApiTestcase),
    path('apitestplan/run/', views_interfacetestplan.startInterfaceTestplan),
    path('apitestplan/run/<str:suit_id>/', views_interfacetestplan.runTestplan),
    path('apitestplan/get/<str:suit_id>/', views_interfacetestplan.getProgress),
    path('report/', views_interfacereport.reportView, name='apireport'),
    path('report/getTableData/', views_interfacereport.loadReport),
    path('report/getReportDetail/<str:report_id>/', views_interfacereport.getReportDetail, name='reportdetail'),
    path('report/del/', views_interfacereport.deleteReport),
    path('apiperformance/', views_performance.apiPerformance, name='apiperformance'),
    path('apiperformance/report/', views_performance.report, name='performancereport'),
    path('apiperformance/search/', views_performance.searchPerformanceInterface),
    path('apiperformance/generate/', views_performance.generateJmeterFile),
    path('apiperformance/prepare/', views_performance.prepareJmeter),
    path('apiperformance/start/', views_performance.startTestJmeter),
    path('apiperformance/progress/', views_performance.showProgress),
    path('performance/viewlog/', views_performance.viewJmeterLog, name='viewjmeterlog'),
    path('apptestcase/', views_apptestcase.getAppView, name='apptestcase'),
    path('apptestcase/getSearchSelect/', views_apptestcase.loadAppOptions),
    path('apptestcase/getTableData/', views_apptestcase.loadAppTestcaseTable),
    path('apptestcase/addApptestcase/', views_apptestcase.addApptestcase),
    path('apptestcase/delApptestcase/', views_apptestcase.deleteApptestcase),
    path('apptestcase/showModAppTestcase/',views_apptestcase.showModAppTestcase),
    path('apptestcase/modApptestcase/', views_apptestcase.modApptestcase),
    path('apptestcase/showCopyAppTestcase/', views_apptestcase.showCopyAppTestcase),
    path('apptestcase/copyApptestcase/', views_apptestcase.copyApptestcase),
    path('apptestcase/run_apptestcase/<int:app_testcase_code>', views_apptestcase.runApptestcase),
    path('apptestcase/runAllTestcase/', views_apptestcase.runAllTestcase),
    path('webtestcase/', views_webtestcase.getWebView, name='webtestcase'),
    path('webtestcase/getSearchSelect/', views_webtestcase.loadWebOptions),
    path('webtestcase/getTableData/', views_webtestcase.loadWebTestcaseTable),
    path('webtestcase/addWebtestcase/', views_webtestcase.addWebtestcase),
    path('webtestcase/delWebtestcase/', views_webtestcase.deleteWebtestcase),
    path('webtestcase/showModWebTestcase/', views_webtestcase.showModWebTestcase),
    path('webtestcase/modWebtestcase/', views_webtestcase.modWebtestcase),
    path('webtestcase/showCopyWebTestcase/', views_webtestcase.showCopyWebTestcase),
    path('webtestcase/copyWebtestcase/', views_webtestcase.copyWebtestcase),
    path('webtestcase/run_webtestcase/<int:web_testcase_code>', views_webtestcase.runWebtestcase),
    path('webtestcase/runAllTestcase/', views_webtestcase.runAllTestcase),
    path('worktask/', views_worktask.worktaskView, name='worktask'),
    path('worktask/getTableData/', views_worktask.loadWroktask),
    path('worktask/add/', views_worktask.addWroktask),
    path('worktask/mod/', views_worktask.updateWorktask),
    path('worktask/del/', views_worktask.deleteWorktask),
    path('worktask/getSearchSelect/', views_worktask.loadWeekSearch),
    path('worktask/getSelect/', views_worktask.loadOptions),
    path('quality/', views_quality.loginView, name='quality'),

    path('sendemail/',views_sendemail.sendReportToEmail,name='sendemail'),
    
    # 环境配置 - 主页面（重定向到Python方法库）
    path('envconfig/', views_envconfig.showEnvConfig, name='envconfig'),
    
    # 环境配置 - Python自定义方法库
    path('envconfig/pythonfunc/', views_envconfig.showPythonFunc, name='python_func'),
    path('envconfig/pythonfunc/list/', views_envconfig.loadPythonFuncList),
    path('envconfig/pythonfunc/add/', views_envconfig.addPythonFunc),
    path('envconfig/pythonfunc/update/', views_envconfig.updatePythonFunc),
    path('envconfig/pythonfunc/delete/', views_envconfig.deletePythonFunc),
    path('envconfig/pythonfunc/toggle/', views_envconfig.togglePythonFuncStatus),
    path('envconfig/pythonfunc/detail/', views_envconfig.getPythonFuncDetail),
    path('envconfig/pythonfunc/debug/', views_envconfig.debugPythonFunc),
    
    # 环境配置 - 全局常量变量库
    path('envconfig/globalvar/', views_envconfig.showGlobalVar, name='global_var'),
    path('envconfig/globalvar/list/', views_envconfig.loadGlobalVarList),
    path('envconfig/globalvar/add/', views_envconfig.addGlobalVar),
    path('envconfig/globalvar/update/', views_envconfig.updateGlobalVar),
    path('envconfig/globalvar/delete/', views_envconfig.deleteGlobalVar),
    path('envconfig/globalvar/toggle/', views_envconfig.toggleGlobalVarStatus),
    path('envconfig/globalvar/detail/', views_envconfig.getGlobalVarDetail),
    path('envconfig/globalvar/import/', views_envconfig.batchImportGlobalVars),
    path('envconfig/globalvar/export/', views_envconfig.exportGlobalVars),
    path('envconfig/globalvar/categories/', views_envconfig.getGlobalVarCategories),
    path('envconfig/addenv/', views_envconfig.addEnv),
    path('envconfig/getenvs/', views_envconfig.getEnvs),
]