# Generated by Django 4.2.23 on 2026-06-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0002_envglobalvariables_env_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envglobalvariables',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序序号'),
        ),
    ]
