# Generated by Django 4.2.23 on 2026-07-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0003_envglobalvariables_sort_order'),
    ]

    operations = [
    ]
